
server:
  port: 8084

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update